[package]
name = "ruoqa"
version = "0.1.2"
edition = "2024"
rust-version = "1.96"
license = "GPL-3.0-or-later"
description = "Async openQA REST API client"
repository = "https://github.com/mimi1vx/ruoqa"
readme = "README.md"
keywords = ["openqa", "client", "api", "async", "hmac"]
categories = ["api-bindings", "web-programming::http-client"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bytes = "1.12.1"
hmac = "0.13.0"
httpdate = "1.0.3"
reqwest = "0.13.4"
rust-ini = "0.21.3"
serde = { version = "1.0.229", features = ["derive"] }
serde-saphyr = "1.0.0"
serde_json = "1.0.151"
sha1 = "0.11.0"
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["time"] }
tracing = "0.1.44"
url = "2.5.8"
zeroize = { version = "1.9.0", features = ["derive"] }

[dev-dependencies]
rcgen = "0.14.8"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tokio-rustls = "0.26.4"
tracing-test = { version = "0.2.6", features = ["no-env-filter"] }
wiremock = "0.6.5"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "warn"
